version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    go-dependencies:
      patterns:
      - "*"
  open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github:
        patterns:
          - "actions/*"
          - "github/*"
    schedule:
      interval: "daily"
