# GoRelease Build Configuration
# Refer https://goreleaser.com/customization/templates template variables.
# Refer https://goreleaser.com/customization/ for the fields.
project_name: fsoc
dist: builds
builds:
- id: fsoc-binaries
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: windows
    goarch: arm64
  binary: fsoc-{{.Os}}-{{.Arch}}
  no_unique_dist_dir: true
  ldflags:
  - -s
  - -w
  - -X {{ .Env.VERSION_PKG_PATH }}.defVersion={{ .Version }}
  - -X {{ .Env.VERSION_PKG_PATH }}.defGitHash={{ .Env.GIT_HASH }}
  - -X {{ .Env.VERSION_PKG_PATH }}.defGitBranch={{ .Env.GIT_BRANCH }}
  - -X {{ .Env.VERSION_PKG_PATH }}.defBuildHost={{ .Env.BUILD_HOST }}
  - -X {{ .Env.VERSION_PKG_PATH }}.defIsDev={{ .Env.BUILD_IS_DEV }}
  - -X {{ .Env.VERSION_PKG_PATH }}.defGitDirty={{ .Env.GIT_DIRTY }}
  - -X {{ .Env.VERSION_PKG_PATH }}.defGitTimestamp={{ .Env.GIT_TIMESTAMP }}
  - -X {{ .Env.VERSION_PKG_PATH }}.defBuildTimestamp={{ .Env.BUILD_TIMESTAMP }}
  flags:
  - -trimpath
  env:
  - CGO_ENABLED=0

archives:
- id: fsoc-binary-archives
  name_template: 'fsoc-{{ .Os }}-{{ .Arch }}'
  format: binary
  builds:
  - fsoc-binaries
- id: fsoc-archives
  name_template: 'fsoc-{{ .Os }}-{{ .Arch }}'
  format: tar.gz
  builds:
  - fsoc-binaries
  format_overrides:
  - goos: windows
    format: zip

brews:
- name: fsoc
  ids:
  - fsoc-archives
  homepage: https://github.com/cisco-open/fsoc
  description: "Cisco FSO Platform Developer's Control Tool"
  license: "Apache-2.0"
  commit_author:
    name: cisco-service
    email: 111539563+cisco-service@users.noreply.github.com
  commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
  folder: Formula
  repository:
    owner: cisco-open
    name: homebrew-tap
    branch: "{{ .ProjectName }}/{{ .Tag }}"
    token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    pull_request:
      enabled: true
      base:
        owner: cisco-open
        name: homebrew-tap
        branch: main
  install: |
    Dir.glob("fsoc-*-*") do |f|
      bin.install f => "fsoc"
    end
  test: |
    system "#{bin}/fsoc", "version"
